name: ci

on:
  pull_request:
    types: [opened, reopened]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.louisgallet.fr
          username: lgallet
          password: ${{ secrets.GITEA_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gitea.louisgallet.fr/ooth/ooth-nextjs:staging